apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-04-10T11:05:41Z"
  generation: 4
  labels:
    app: aggregator
  name: aggregator
  namespace: default
  resourceVersion: "10706"
  selfLink: /apis/apps/v1/namespaces/default/deployments/aggregator
  uid: 37cce76a-7b1b-11ea-9c44-42010a800052
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aggregator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aggregator
    spec:
      containers:
      - env:
        - name: USER_URL
          valueFrom:
            configMapKeyRef:
              key: USER_URL
              name: aggregator-config-dbpq
        - name: ORDER_URL
          valueFrom:
            configMapKeyRef:
              key: ORDER_URL
              name: aggregator-config-dbpq
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              key: JAEGER_HOST
              name: aggregator-config-dbpq
        image: ashish71294/aggregator-services:1.2
        imagePullPolicy: IfNotPresent
        name: aggregator-services-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-04-10T11:05:41Z"
    lastUpdateTime: "2020-04-10T11:11:01Z"
    message: ReplicaSet "aggregator-668774fd69" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-10T11:13:19Z"
    lastUpdateTime: "2020-04-10T11:13:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
