apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-10T11:11:34Z"
  labels:
    app: aggregator
  name: aggregator-service
  namespace: default
  resourceVersion: "10429"
  selfLink: /api/v1/namespaces/default/services/aggregator-service
  uid: 09ef12ec-7b1c-11ea-9c44-42010a800052
spec:
  clusterIP: 10.99.12.169
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31028
    port: 80
    protocol: TCP
    targetPort: 8001
  selector:
    app: aggregator
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.232.145.9
