apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-11T08:26:47Z"
  labels:
    app: user
  name: user-service
  namespace: default
  resourceVersion: "278512"
  selfLink: /api/v1/namespaces/default/services/user-service
  uid: 2f4f0b01-7bce-11ea-9c44-42010a800052
spec:
  clusterIP: 10.99.3.227
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
