apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-09T18:33:16Z"
  generation: 2
  labels:
    app: user
  name: user
  namespace: default
  resourceVersion: "7606"
  selfLink: /apis/apps/v1/namespaces/default/deployments/user
  uid: 93ecfad1-7a90-11ea-a7a5-42010a800075
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: user-config-hhhz
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: user-config-hhhz
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: user-config-hhhz
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              key: JAEGER_HOST
              name: user-config-hhhz
        image: ashish71294/user-services:1.3
        imagePullPolicy: IfNotPresent
        name: user-services-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-09T18:33:18Z"
    lastUpdateTime: "2020-04-09T18:33:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-09T18:33:16Z"
    lastUpdateTime: "2020-04-09T18:33:18Z"
    message: ReplicaSet "user-654dcc6d49" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
